/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 1ef82bfec64f6e96ed488ea9a09d19af)
interface __BaseEnv_Env {
	Database: Hyperdrive;
	MONS_CATALOG_SCHEMA: "mons_catalog";
	MONS_STAGE: "dev" | "production" | "local";
}
declare namespace Cloudflare {
	interface DevEnv {
		Database: Hyperdrive;
		MONS_CATALOG_SCHEMA: "mons_catalog";
		MONS_STAGE: "dev";
	}
	interface ProductionEnv {
		Database: Hyperdrive;
		MONS_CATALOG_SCHEMA: "mons_catalog";
		MONS_STAGE: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MONS_CATALOG_SCHEMA" | "MONS_STAGE">> {}
}
