export const tableNutrients: ReadonlyArray<{ field: string; label: string; unit: string }> = [
  { field: 'fiber', label: 'Fiber', unit: 'g' },
  { field: 'total_sugars', label: 'Sugars', unit: 'g' },
  { field: 'added_sugars', label: 'Added sugars', unit: 'g' },
  { field: 'saturated_fat', label: 'Saturated fat', unit: 'g' },
  { field: 'trans_fat', label: 'Trans fat', unit: 'g' },
  { field: 'dietary_cholesterol', label: 'Cholesterol', unit: 'mg' },
  { field: 'sodium', label: 'Sodium', unit: 'mg' },
  { field: 'potassium', label: 'Potassium', unit: 'mg' },
  { field: 'calcium', label: 'Calcium', unit: 'mg' },
  { field: 'iron', label: 'Iron', unit: 'mg' },
  { field: 'magnesium', label: 'Magnesium', unit: 'mg' },
  { field: 'zinc', label: 'Zinc', unit: 'mg' },
  { field: 'vitamin_c_ascorbic_acid', label: 'Vitamin C', unit: 'mg' },
  { field: 'vitamin_d_calciferol', label: 'Vitamin D', unit: 'mcg' },
  { field: 'vitamin_b6', label: 'Vitamin B6', unit: 'mg' },
  { field: 'vitamin_b12_cobalamin', label: 'Vitamin B12', unit: 'mcg' },
  { field: 'folate_dfe', label: 'Folate (DFE)', unit: 'mcg' },
  { field: 'vitamin_a_retinol', label: 'Retinol', unit: 'mcg' },
  { field: 'vitamin_e_tocopherol', label: 'Vitamin E', unit: 'mg' },
  { field: 'vitamin_k_phylloquinone', label: 'Vitamin K', unit: 'mcg' },
]
