/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    Ai: import('@cloudflare/workers-types').Ai
    Api: import('@cloudflare/workers-types').Service
    ClerkSecretKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    Database: import('@cloudflare/workers-types').Hyperdrive
    Media: import('@cloudflare/workers-types').R2Bucket
    PublicConfig: {
      clerkPublishableKey: string
      type: 'sst.sst.Linkable'
    }
  }
}

import 'sst'
export {}
