/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    Ai: {
      type: 'sst.cloudflare.Ai'
    }
    Api: {
      type: 'sst.cloudflare.Worker'
      url: string
    }
    ClerkSecretKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    Database: {
      id: string
      type: 'sst.cloudflare.Hyperdrive'
    }
    DatabaseConfig: {
      appSchema: string
      catalogSchema: string
      r2Prefix: string
      scope: string
      type: 'sst.sst.Linkable'
    }
    Media: {
      name: string
      type: 'sst.sst.Linkable'
    }
    PublicConfig: {
      clerkPublishableKey: string
      type: 'sst.sst.Linkable'
    }
  }
}

import 'sst'
export {}
