import { Effect } from 'effect'
import { SqlClient } from 'effect/unstable/sql'

import { validateSchemaName } from './migrations.ts'

const allowedFixtureSchema = (schema: string) =>
  schema.endsWith('_sample') || schema.endsWith('_test')

export const replaceCatalogWithFixture = (schema = 'mons_catalog_sample') =>
  Effect.gen(function* () {
    const safeSchema = yield* validateSchemaName(schema)
    if (!allowedFixtureSchema(safeSchema)) {
      return yield* Effect.fail(
        new Error('Catalog fixtures may only replace schemas ending in _sample or _test'),
      )
    }

    const sql = yield* SqlClient.SqlClient
    const catalog = sql(safeSchema)
    const foods = sql(`${safeSchema}.foods`)
    const brands = sql(`${safeSchema}.brands`)
    const foodGroups = sql(`${safeSchema}.food_groups`)
    const restaurants = sql(`${safeSchema}.restaurants`)
    const portions = sql(`${safeSchema}.portions`)
    const catalogMetadata = sql(`${safeSchema}.catalog_metadata`)

    yield* sql`DROP SCHEMA IF EXISTS ${catalog} CASCADE`
    yield* sql`CREATE SCHEMA ${catalog}`
    yield* sql`CREATE TABLE ${catalogMetadata} (
      release_id text PRIMARY KEY,
      schema_version text NOT NULL,
      storage_version integer NOT NULL,
      built_at timestamptz NOT NULL,
      loaded_at timestamptz NOT NULL,
      raw_rows bigint NOT NULL,
      branded_rows bigint NOT NULL,
      restaurant_snapshot_id text,
      restaurant_rows bigint NOT NULL,
      restaurant_rejected_rows bigint NOT NULL
    )`
    yield* sql`INSERT INTO ${catalogMetadata}
      VALUES ('sample-catalog-v1', 'sample', 8, '2026-01-01T00:00:00Z',
              '2026-01-01T00:00:00Z', 2, 3, 'sample-restaurants-v1', 1, 0)`
    yield* sql`CREATE TABLE ${foodGroups} (
      food_group_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug text NOT NULL UNIQUE,
      name text NOT NULL
    )`
    yield* sql`CREATE TABLE ${brands} (
      brand_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL,
      normalized_name text NOT NULL UNIQUE
    )`
    yield* sql`CREATE TABLE ${restaurants} (
      restaurant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL
    )`
    yield* sql`CREATE UNIQUE INDEX sample_restaurants_name_idx
      ON ${restaurants} ((lower(name) COLLATE "C"))`
    yield* sql`CREATE TABLE ${foods} (
      food_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      dataset_kind text NOT NULL,
      source_key smallint NOT NULL,
      source_record_id text NOT NULL,
      name text NOT NULL,
      search_aliases text NOT NULL DEFAULT '',
      food_group_id bigint NOT NULL REFERENCES ${foodGroups}(food_group_id),
      brand_id bigint REFERENCES ${brands}(brand_id),
      restaurant_id bigint REFERENCES ${restaurants}(restaurant_id),
      gtin char(14),
      nutrient_basis_amount double precision NOT NULL,
      nutrient_basis_unit text NOT NULL,
      calories double precision,
      carbohydrates_available double precision,
      carbohydrates_total double precision,
      carbohydrates_net_calculated double precision,
      fiber double precision,
      protein double precision,
      sodium double precision,
      total_fat double precision,
      search_document tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('simple', search_aliases), 'B')
      ) STORED,
      UNIQUE (source_key, source_record_id)
    )`
    yield* sql`CREATE INDEX sample_foods_search_idx ON ${foods} USING gin (search_document)`
    yield* sql`CREATE INDEX sample_foods_name_idx ON ${foods} ((lower(name) COLLATE "C"), food_id)`
    yield* sql`CREATE INDEX sample_brands_name_idx ON ${brands} ((lower(name) COLLATE "C"), brand_id)`
    yield* sql`CREATE INDEX sample_foods_brand_idx ON ${foods} (brand_id, food_id)`
    yield* sql`CREATE INDEX sample_foods_group_idx ON ${foods} (food_group_id, food_id)`
    yield* sql`CREATE INDEX sample_foods_restaurant_idx ON ${foods} (restaurant_id, food_id)`
    yield* sql`CREATE TABLE ${portions} (
      portion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      food_id bigint NOT NULL REFERENCES ${foods}(food_id) ON DELETE CASCADE,
      ordinal integer NOT NULL,
      name text NOT NULL,
      amount double precision NOT NULL,
      unit text NOT NULL,
      UNIQUE (food_id, ordinal)
    )`
    yield* sql`INSERT INTO ${foodGroups} (food_group_id, slug, name) VALUES
      (1, 'fruit', 'Fruit'),
      (2, 'eggs', 'Eggs'),
      (3, 'grains_and_starches', 'Grains & Starches'),
      (4, 'dairy', 'Dairy'),
      (5, 'prepared_foods', 'Prepared Foods')`
    yield* sql`INSERT INTO ${brands} (brand_id, name, normalized_name) VALUES
      (1, 'Sample Pantry', 'sample pantry'),
      (2, 'Sample Dairy', 'sample dairy'),
      (3, 'Sample Bakery', 'sample bakery')`
    yield* sql`INSERT INTO ${restaurants} (restaurant_id, name) VALUES (1, 'Sample Grill')`
    yield* sql`INSERT INTO ${foods}
      (food_id, dataset_kind, source_key, source_record_id, name, search_aliases, food_group_id,
       brand_id, restaurant_id, gtin,
       nutrient_basis_amount, nutrient_basis_unit, calories, carbohydrates_total,
       carbohydrates_net_calculated, fiber, protein, sodium, total_fat)
      VALUES
      (1, 'raw', 30001, 'raw-apple', 'Sample Apple', 'Fresh apple', 1, NULL, NULL, NULL, 100, 'g', 52, 13.8, 11.4, 2.4, 0.3, 1, 0.2),
      (2, 'raw', 30001, 'raw-egg', 'Sample Egg', '', 2, NULL, NULL, NULL, 100, 'g', 143, 0.7, 0.7, 0, 12.6, 142, 9.5),
      (3, 'branded', 30001, 'branded-oats', 'Rolled Oats', '', 3, 1, NULL,
       '00000000000003', 100, 'g', 379, 67.7, 57.6, 10.1, 13.2, 6, 6.5),
      (4, 'branded', 30001, 'branded-milk', 'Whole Milk', '', 4, 2, NULL,
       '00000000000004', 100, 'g', 61, 4.8, 4.8, 0, 3.2, 43, 3.3),
      (5, 'branded', 30001, 'branded-bread', 'Bread', '', 3, 3, NULL,
       '00000000000005', 100, 'g', 265, 49, 46.3, 2.7, 9, 491, 3.2),
      (6, 'restaurant', 30001, 'restaurant-burger', 'Classic Burger', '', 5, NULL, 1,
       NULL, 1, 'serving', 620, 48, 45, 3, 31, 980, 34)`
    yield* sql`INSERT INTO ${portions}
      (food_id, ordinal, name, amount, unit) VALUES
      (1, 0, '1 medium apple', 182, 'g'),
      (2, 0, '1 large egg', 50, 'g'),
      (3, 0, '1/2 cup', 40, 'g'),
      (4, 0, '1 cup', 244, 'g'),
      (5, 0, '1 slice', 28, 'g'),
      (6, 0, '1 burger', 1, 'serving')`
  })
