import { describe, expect, layer } from '@effect/vitest'
import { Effect, Layer } from 'effect'
import { SqlClient } from 'effect/unstable/sql'

import { createDatabaseLayer } from './core/client.ts'
import { CatalogReader, catalogReaderLayer } from './features/catalog/repository.ts'
import { LibraryRepository, libraryRepositoryLayer } from './features/library/repository.ts'
import {
  LegacyFoodLogRepository,
  legacyFoodLogRepositoryLayer,
} from './features/meals/legacy-food-log-repository.ts'
import {
  MealEstimateRepository,
  mealEstimateRepositoryLayer,
} from './features/meals/meal-estimate-repository.ts'
import { MealLogRepository, mealLogRepositoryLayer } from './features/meals/meal-log-repository.ts'
import {
  NutritionPlanRepository,
  nutritionPlanRepositoryLayer,
} from './features/nutrition/repository.ts'
import { ProfileRepository, profileRepositoryLayer } from './features/profile/repository.ts'
import { WeightRepository, weightRepositoryLayer } from './features/weight/repository.ts'
import { WorkoutRepository, workoutRepositoryLayer } from './features/workouts/repository.ts'
import { migrateApplicationDatabase } from './migrations.ts'

const databaseUrl = process.env.MONS_TEST_DATABASE_URL
const integration = databaseUrl === undefined ? describe.skip : describe
const schema = 'mons_catalog_effect_test'
const appSchema = 'mons_app_effect_test'

const fixtureLayer = Layer.effectDiscard(
  Effect.acquireRelease(
    Effect.gen(function* () {
      const sql = yield* SqlClient.SqlClient
      const catalog = sql(schema)
      const application = sql(appSchema)
      const foods = sql(`${schema}.foods`)
      const brands = sql(`${schema}.brands`)
      const foodGroups = sql(`${schema}.food_groups`)
      const restaurants = sql(`${schema}.restaurants`)
      const portions = sql(`${schema}.portions`)
      const catalogMetadata = sql(`${schema}.catalog_metadata`)
      yield* sql`DROP SCHEMA IF EXISTS ${catalog} CASCADE`
      yield* sql`DROP SCHEMA IF EXISTS ${application} CASCADE`
      yield* sql`CREATE SCHEMA ${catalog}`
      yield* sql`CREATE TABLE ${catalogMetadata} (
        release_id text PRIMARY KEY, restaurant_snapshot_id text
      )`
      yield* sql`INSERT INTO ${catalogMetadata} VALUES ('2026-08-27-test0001', NULL)`
      yield* sql`CREATE TABLE ${foodGroups} (
        food_group_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug text NOT NULL UNIQUE, name text NOT NULL
      )`
      yield* sql`CREATE TABLE ${brands} (
        brand_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL, normalized_name text NOT NULL UNIQUE
      )`
      yield* sql`CREATE TABLE ${restaurants} (
        restaurant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL
      )`
      yield* sql`CREATE TABLE ${foods} (
        brand_id bigint REFERENCES ${brands}(brand_id),
        food_group_id bigint NOT NULL REFERENCES ${foodGroups}(food_group_id),
        calories double precision, carbohydrates_available double precision,
        carbohydrates_total double precision, dataset_kind text NOT NULL,
        food_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fiber double precision, gtin char(14), name text NOT NULL,
        search_aliases text NOT NULL DEFAULT '',
        restaurant_id bigint REFERENCES ${restaurants}(restaurant_id),
        nutrient_basis_amount double precision NOT NULL, nutrient_basis_unit text NOT NULL,
        protein double precision, source_key smallint NOT NULL,
        source_record_id text NOT NULL,
        sodium double precision, total_fat double precision,
        search_document tsvector GENERATED ALWAYS AS (
          setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
          setweight(to_tsvector('simple', search_aliases), 'B')
        ) STORED
      )`
      yield* sql`CREATE INDEX foods_search_document_idx ON ${foods} USING gin (search_document)`
      yield* sql`CREATE INDEX foods_name_prefix_idx ON ${foods} ((lower(name) COLLATE "C"), food_id)`
      yield* sql`CREATE INDEX brands_name_prefix_idx ON ${brands} ((lower(name) COLLATE "C"), brand_id)`
      yield* sql`CREATE TABLE ${portions} (
        portion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        amount double precision NOT NULL, food_id bigint NOT NULL,
        name text NOT NULL, ordinal integer NOT NULL, unit text NOT NULL
      )`
      yield* sql`INSERT INTO ${foodGroups} (food_group_id, slug, name) VALUES
        (1, 'fruit', 'Fruit'), (2, 'eggs', 'Eggs'),
        (3, 'herbs_and_spices', 'Herbs & Spices'),
        (4, 'prepared_foods', 'Prepared Foods')`
      yield* sql`INSERT INTO ${brands} (brand_id, name, normalized_name) VALUES
        (1, 'Example', 'example'), (2, 'Broken', 'broken'),
        (3, 'USDA', 'usda'), (4, 'OFF', 'off')`
      yield* sql`INSERT INTO ${restaurants} (restaurant_id, name) VALUES (1, 'Example Grill')`
      yield* sql`INSERT INTO ${foods}
        (brand_id, food_group_id, calories, carbohydrates_total, dataset_kind, food_id, gtin,
         name, nutrient_basis_amount, nutrient_basis_unit, protein, source_key,
         source_record_id, total_fat, restaurant_id)
        VALUES
        (1, 1, 52, 14, 'branded', 1, '00000000000001', 'Apple', 100, 'g', 0.3, 30000, 'b-1', 0.2, NULL),
        (1, 1, 237, 34, 'branded', 2, '00000000000002', 'Apple Pie', 100, 'g', 2.4, 30000, 'b-2', 11, NULL),
        (NULL, 1, 57, 15, 'raw', 3, NULL, 'Raw Apple', 100, 'g', 0.3, 30000, 'r-1', 0.1, NULL),
        (2, 4, NULL, NULL, 'branded', 4, '00000000000004', 'Broken Food', 100, 'g', NULL, 2, 'bad-1', NULL, NULL),
        (3, 2, 90, 0.4, 'branded', 5, '00000000000005', 'Egg Fried', 100, 'g', 6.3, 1, 'usda-1', 6.8, NULL),
        (4, 2, 90, 0.4, 'branded', 6, '00000000000006', 'Egg Fried', 100, 'g', 6.3, 2, 'off-1', 6.8, NULL),
        (NULL, 3, 295, NULL, 'raw', 7, NULL, 'Cardamom Seed', 100, 'g', 10.8, 9, 'au-1', 6.7, NULL),
        (NULL, 4, 620, 48, 'restaurant', 8, NULL, 'Apple Burger', 1, 'serving', 31, 11, 'menu-1', 34, 1),
        (NULL, 3, 25, 4, 'raw', 9, NULL, 'Ground Cardamom Leaves', 100, 'g', 2, 4, 'leaf-1', 0.2, NULL)`
      yield* sql`UPDATE ${foods} SET search_aliases = 'Ground cardamom' WHERE food_id = 7`
      yield* sql`UPDATE ${foods} SET carbohydrates_available = 40 WHERE food_id = 7`
      yield* sql`UPDATE ${foods} SET fiber = 2.4, sodium = 1 WHERE food_id = 1`
      yield* sql`INSERT INTO ${portions} (amount, food_id, name, ordinal, unit) VALUES
        (182, 1, '1 medium apple', 0, 'g'),
        (30, 1, '1 cup, sliced', 1, 'g'),
        (15, 3, '1 slice', 0, 'g'),
        (1, 8, '1 burger', 0, 'serving')`
      yield* migrateApplicationDatabase(appSchema)
    }),
    () =>
      Effect.gen(function* () {
        const sql = yield* SqlClient.SqlClient
        yield* sql`DROP SCHEMA IF EXISTS ${sql(schema)} CASCADE`
        yield* sql`DROP SCHEMA IF EXISTS ${sql(appSchema)} CASCADE`
      }).pipe(Effect.orDie),
  ),
)

const databaseLayer = createDatabaseLayer({
  connectionString: databaseUrl ?? 'postgresql://mons:mons_local@localhost:5432/mons',
})
const repositoryLayers = Layer.mergeAll(
  catalogReaderLayer(schema),
  profileRepositoryLayer({
    appSchema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  nutritionPlanRepositoryLayer({ appSchema }),
  legacyFoodLogRepositoryLayer({
    appSchema,
    catalogSchema: schema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  libraryRepositoryLayer({
    appSchema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  weightRepositoryLayer({
    appSchema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  workoutRepositoryLayer({
    appSchema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  mealEstimateRepositoryLayer({
    appSchema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
  mealLogRepositoryLayer({
    appSchema,
    catalogSchema: schema,
    now: () => new Date('2026-08-04T12:00:00Z'),
  }),
)
const testLayer = Layer.merge(fixtureLayer, repositoryLayers).pipe(
  Layer.provideMerge(databaseLayer),
)

integration('feature repositories with PostgreSQL', () => {
  layer(testLayer)((it) => {
    it.effect('resolves complete barcode nutrition', () =>
      Effect.gen(function* () {
        const catalog = yield* CatalogReader
        expect(yield* catalog.activeReleaseId()).toBe('2026-08-27-test0001')
        const food = yield* catalog.findByGtin('00000000000001')
        expect(food).toMatchObject({
          food_id: '1',
          name: 'Apple',
          nutrients: [
            { amount: 52, field: 'calories', name: 'Food energy', unit: 'kcal' },
            {
              amount: 14,
              field: 'carbohydrates_total',
              name: 'Total carbohydrate',
              unit: 'g',
            },
            { amount: 2.4, field: 'fiber', name: 'Dietary fibre', unit: 'g' },
            { amount: 0.3, field: 'protein', name: 'Protein', unit: 'g' },
            { amount: 1, field: 'sodium', name: 'Sodium', unit: 'mg' },
            { amount: 0.2, field: 'total_fat', name: 'Total fat', unit: 'g' },
          ],
        })
        expect(yield* catalog.findById('branded', '1')).toMatchObject({
          food_id: '1',
          name: 'Apple',
        })
      }),
    )

    it.effect('searches deterministically, validates data, and prioritizes USDA', () =>
      Effect.gen(function* () {
        const catalog = yield* CatalogReader
        const raw = yield* catalog.search({ kind: 'raw', limit: 10, query: 'apple' })
        expect(raw.map((food) => food.food_id)).toEqual(['3'])
        const fallback = yield* catalog.search({ kind: 'raw', limit: 10, query: 'cardamom' })
        expect(fallback[0]?.carbohydrates_total).toBe(40)
        const ingredientAlias = yield* catalog.search({
          kind: 'raw',
          limit: 10,
          query: 'ground cardamom',
        })
        expect(ingredientAlias.map((food) => food.food_id)).toEqual(['7', '9'])
        const broken = yield* catalog.search({ kind: 'branded', limit: 10, query: 'broken' })
        expect(broken).toEqual([])
        const eggs = yield* catalog.search({ kind: 'branded', limit: 10, query: 'egg fried' })
        expect(eggs.map((food) => food.food_id)).toEqual(['5', '6'])
        const partial = yield* catalog.search({ kind: 'branded', limit: 10, query: 'egg fri' })
        expect(partial.map((food) => food.food_id)).toEqual(['5', '6'])
        expect(partial[0]).toMatchObject({
          calories: 90,
          carbohydrates_total: 0.4,
          default_portion: null,
          protein: 6.3,
          total_fat: 6.8,
        })
        const typo = yield* catalog.search({ kind: 'branded', limit: 10, query: 'egg friedd' })
        expect(typo).toEqual([])
        const all = yield* catalog.search({ limit: 10, query: 'apple' })
        expect(all.map((food) => food.dataset_kind)).toContain('restaurant')
        const fruit = yield* catalog.search({ foodGroupId: '1', limit: 10, query: 'apple' })
        expect(fruit.every((food) => food.food_group_id === '1')).toBe(true)
        const exampleBrand = yield* catalog.search({ brandId: '1', limit: 10, query: 'apple' })
        expect(exampleBrand.map((food) => food.food_id)).toEqual(['1', '2'])
        expect(yield* catalog.listBrands({ limit: 10, query: 'exam' })).toEqual([
          { brand_id: '1', food_count: '2', name: 'Example' },
        ])
        expect(yield* catalog.listFoodGroups()).toContainEqual({
          food_count: '3',
          food_group_id: '1',
          name: 'Fruit',
          slug: 'fruit',
        })
        const restaurant = yield* catalog.search({ kind: 'restaurant', limit: 10, query: 'grill' })
        expect(restaurant[0]).toMatchObject({
          brand: 'Example Grill',
          dataset_kind: 'restaurant',
          default_portion: { amount: 1, name: '1 burger', unit: 'serving' },
          nutrient_basis: { amount: 1, unit: 'serving' },
        })
        expect(yield* catalog.findById('restaurant', '8')).toMatchObject({
          brand: 'Example Grill',
          name: 'Apple Burger',
        })
      }),
    )

    it.effect('maps Clerk users to stable internal profiles', () =>
      Effect.gen(function* () {
        const profiles = yield* ProfileRepository
        const first = yield* profiles.ensureForClerkUser('user_database_test')
        const repeated = yield* profiles.ensureForClerkUser('user_database_test')
        const second = yield* profiles.ensureForClerkUser('user_database_test_two')
        expect(repeated).toBe(first)
        expect(second).not.toBe(first)
        expect(yield* profiles.belongsToClerkUser(first, 'user_database_test')).toBe(true)
        expect(yield* profiles.belongsToClerkUser(first, 'user_database_test_two')).toBe(false)
      }),
    )

    it.effect('persists nutrition, food, and weight logs deterministically', () =>
      Effect.gen(function* () {
        const foodLog = yield* LegacyFoodLogRepository
        const nutrition = yield* NutritionPlanRepository
        const weight = yield* WeightRepository
        const profileId = '00000000-0000-4000-8000-000000000001'
        const food = yield* foodLog.save(profileId, {
          datasetKind: 'branded',
          entryId: '00000000-0000-4000-8000-000000000002',
          foodId: '1',
          loggedAt: new Date('2026-08-04T12:00:00Z'),
          mealCategory: 'lunch',
          quantityGrams: 150,
        })
        expect(food).toMatchObject({ calories_per_100g: 52, name: 'Apple', quantity_grams: 150 })
        const plan = yield* nutrition.save(profileId, {
          birthDate: '1998-02-18',
          calculatedAt: new Date('2026-08-04T12:00:00Z'),
          calorieTargetKcal: 1460,
          currentWeightKg: 56.7,
          dailyActivity: 'mostly_sedentary',
          estimatedExpenditureKcal: 1772,
          estimatedWeeks: 16.6,
          exerciseFrequency: 'none',
          heightCm: 160,
          metabolicSex: 'female',
          rateLimited: false,
          restingEnergyKcal: 1266,
          targetWeightKg: 52,
          weeklyWeightChangePercent: 0.5,
          weightGoal: 'lose',
        })
        expect(plan).toMatchObject({ calorie_target_kcal: 1460, estimated_expenditure_kcal: 1772 })
        yield* weight.save(profileId, {
          entryId: '00000000-0000-4000-8000-000000000031',
          measuredAt: new Date('2026-08-03T11:00:00Z'),
          weightKg: 56.9,
        })
        yield* weight.save(profileId, {
          entryId: '00000000-0000-4000-8000-000000000030',
          measuredAt: new Date('2026-08-04T11:00:00Z'),
          weightKg: 56.7,
        })
        const weights = yield* weight.list(
          profileId,
          new Date('2026-08-01T00:00:00Z'),
          new Date('2026-09-01T00:00:00Z'),
        )
        expect(weights.map((entry) => entry.weight_kg)).toEqual([56.9, 56.7])
      }),
    )

    it.effect('persists custom foods and calculates recipe portions from measured yield', () =>
      Effect.gen(function* () {
        const profileId = '00000000-0000-4000-8000-000000000001'
        const library = yield* LibraryRepository
        const foodLog = yield* LegacyFoodLogRepository
        const profiles = yield* ProfileRepository
        yield* profiles.ensure(profileId)
        const custom = yield* library.saveCustomFood(profileId, {
          barcode: '00000000000009',
          brand: 'Home',
          calories: 100,
          carbohydrates: 20,
          foodId: '00000000-0000-4000-8000-000000000090',
          imageDataBase64: null,
          name: 'Test Ingredient',
          nutritionLabelImageDataBase64: null,
          portions: [{ amount: 30, name: '1 scoop', unit: 'g' }],
          protein: 5,
          totalFat: 2,
        })
        expect(custom.portions).toMatchObject([{ amount: 30, name: '1 scoop' }])
        const recipe = yield* library.saveRecipe(profileId, {
          freeformIngredients: [
            {
              calories: 0,
              carbohydrates: 0,
              ingredientId: '00000000-0000-4000-8000-000000000094',
              name: 'garlic',
              protein: 0,
              quantity: 2,
              text: '2 tbsp garlic',
              totalFat: 0,
              unit: 'tbsp',
            },
          ],
          imageDataBase64: null,
          ingredients: [
            {
              calories: 100,
              carbohydrates: 20,
              foodId: custom.food.food_id,
              ingredientId: '00000000-0000-4000-8000-000000000092',
              name: custom.food.name,
              protein: 5,
              quantityGrams: 200,
              sourceKind: 'custom',
              totalFat: 2,
            },
          ],
          name: 'Measured Recipe',
          notes: '',
          nutrition: {
            calories: 40,
            carbohydrates: 8,
            protein: 2,
            status: 'mixed',
            totalFat: 0.8,
          },
          recipeId: '00000000-0000-4000-8000-000000000091',
          servings: 4,
          totalYieldGrams: 500,
        })
        expect(recipe.recipe).toMatchObject({
          calories_per_100g: 40,
          nutrition_status: 'mixed',
          total_yield_grams: 500,
        })
        expect(recipe.freeformIngredients).toMatchObject([
          { name: 'garlic', quantity: 2, text: '2 tbsp garlic', unit: 'tbsp' },
        ])
        const logged = yield* foodLog.save(profileId, {
          datasetKind: 'recipe',
          entryId: '00000000-0000-4000-8000-000000000093',
          foodId: recipe.recipe.recipe_id,
          loggedAt: new Date('2026-08-04T18:00:00Z'),
          mealCategory: 'dinner',
          quantityGrams: 125,
        })
        expect(logged).toMatchObject({ calories_per_100g: 40, quantity_grams: 125 })
      }),
    )

    it.effect('commits media metadata with a meal and durably queues deletion', () =>
      Effect.gen(function* () {
        const profiles = yield* ProfileRepository
        const estimates = yield* MealEstimateRepository
        const meals = yield* MealLogRepository
        // PostgreSQL canonicalizes UUID output to lowercase while iOS emits uppercase UUID strings.
        const profileId = 'ABCDEFAB-0000-4000-8000-000000000101'
        const estimateId = 'ABCDEFAB-0000-4000-8000-000000000102'
        const mealId = 'ABCDEFAB-0000-4000-8000-000000000103'
        const objectKey = `meals/${profileId}/${estimateId}.jpg`
        yield* profiles.ensure(profileId)
        yield* estimates.save({
          calories: 52,
          carbohydrates: 14,
          description: 'Apple',
          estimateId,
          inputDescription: 'an apple',
          inputKind: 'photo',
          items: [],
          mediaContentType: null,
          mediaObjectKey: null,
          mediaSha256: null,
          observationModel: 'fixture-observer',
          overallConfidence: 1,
          profileId,
          promptVersion: 'fixture-v1',
          protein: 0.3,
          resolutionModel: 'fixture-resolver',
          totalFat: 0.2,
          transcript: null,
          transcriptionModel: null,
        })
        yield* meals.enqueueMediaCleanup(objectKey, new Date('2026-08-05T12:00:00Z'))

        const saved = yield* meals.save(profileId, {
          description: 'Apple',
          estimateId,
          items: [
            {
              datasetKind: 'branded',
              entryId: 'ABCDEFAB-0000-4000-8000-000000000104',
              foodId: '1',
              quantityGrams: 182,
            },
          ],
          loggedAt: new Date('2026-08-04T12:00:00Z'),
          mealCategory: 'lunch',
          mealId,
          media: { contentType: 'image/jpeg', objectKey, sha256: 'fixture-sha256' },
        })
        expect(saved.meal.media_object_key).toBe(objectKey)
        expect(yield* meals.listMediaCleanup(10)).toEqual([])

        expect(yield* meals.delete(profileId, mealId)).toBeDefined()
        expect(yield* meals.listMediaCleanup(10)).toEqual([objectKey])
        expect(yield* estimates.findById(profileId, estimateId)).toBeUndefined()
      }),
    )

    it.effect('persists workout sessions and ordered template hierarchies', () =>
      Effect.gen(function* () {
        const workoutsRepository = yield* WorkoutRepository
        const profileId = '00000000-0000-4000-8000-000000000001'
        yield* workoutsRepository.save(profileId, {
          completedAt: new Date('2026-08-04T14:00:00Z'),
          distanceKilometers: null,
          durationMinutes: 60,
          kind: 'strength',
          sessionId: '00000000-0000-4000-8000-000000000010',
          sets: [
            {
              detail: '8 reps',
              setId: '00000000-0000-4000-8000-000000000011',
              title: 'Bench Press',
              value: '80 kg',
            },
          ],
          startedAt: new Date('2026-08-04T13:00:00Z'),
          title: 'Upper Body',
        })
        const workouts = yield* workoutsRepository.list(
          profileId,
          new Date('2026-08-01T00:00:00Z'),
          new Date('2026-09-01T00:00:00Z'),
        )
        expect(workouts[0]?.sets.map((set) => set.title)).toEqual(['Bench Press'])
        const templateId = 'ABCDEFAB-0000-4000-8000-000000000040'
        yield* workoutsRepository.saveTemplate(profileId, {
          exercises: [
            {
              category: 'Lower Body',
              equipment: 'Barbell',
              exerciseId: 'barbell-squat',
              name: 'Barbell Squat',
              notes: '',
              templateExerciseId: '00000000-0000-4000-8000-000000000041',
              sets: [
                {
                  repetitions: 8,
                  restSeconds: 90,
                  setId: '00000000-0000-4000-8000-000000000042',
                  weightPounds: 135,
                },
                {
                  repetitions: 6,
                  restSeconds: 120,
                  setId: '00000000-0000-4000-8000-000000000043',
                  weightPounds: 155,
                },
              ],
            },
          ],
          name: 'Leg Day',
          templateId,
        })
        const templates = yield* workoutsRepository.listTemplates(profileId)
        expect(templates[0]?.exercises[0]?.sets.map((set) => set.repetitions)).toEqual([8, 6])
        expect(yield* workoutsRepository.deleteTemplate(profileId, templateId)).toBe(true)
      }),
    )
  })
})
