/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false services/api/src/worker-configuration.d.ts` (hash: c1891a1ca6b1a62109a7dc455689e244)
interface __BaseEnv_Env {
  Media: R2Bucket
  Database: Hyperdrive
  Ai: Ai
  AI_GATEWAY_ID: 'mons-dev' | 'mons-production'
  CLERK_PUBLISHABLE_KEY: 'pk_test_YmlnLWNvdy04Mi5jbGVyay5hY2NvdW50cy5kZXYk'
  MONS_APP_SCHEMA: 'mons_app'
  MONS_CATALOG_SCHEMA: 'mons_catalog'
  MONS_DEPLOYMENT_SCOPE: 'dev' | 'production' | 'local'
  MONS_STAGE: 'dev' | 'production' | 'local'
  MONS_STORAGE_PREFIX: 'dev' | 'production' | 'local'
  R2_BUCKET_NAME: 'mons'
  CLERK_SECRET_KEY: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker')
  }
  interface DevEnv {
    Media: R2Bucket
    Database: Hyperdrive
    Ai: Ai
    AI_GATEWAY_ID: 'mons-dev'
    CLERK_PUBLISHABLE_KEY: 'pk_test_YmlnLWNvdy04Mi5jbGVyay5hY2NvdW50cy5kZXYk'
    MONS_APP_SCHEMA: 'mons_app'
    MONS_CATALOG_SCHEMA: 'mons_catalog'
    MONS_DEPLOYMENT_SCOPE: 'dev'
    MONS_STAGE: 'dev'
    MONS_STORAGE_PREFIX: 'dev'
    R2_BUCKET_NAME: 'mons'
    CLERK_SECRET_KEY: string
  }
  interface ProductionEnv {
    Media: R2Bucket
    Database: Hyperdrive
    Ai: Ai
    AI_GATEWAY_ID: 'mons-production'
    CLERK_PUBLISHABLE_KEY: 'pk_test_YmlnLWNvdy04Mi5jbGVyay5hY2NvdW50cy5kZXYk'
    MONS_APP_SCHEMA: 'mons_app'
    MONS_CATALOG_SCHEMA: 'mons_catalog'
    MONS_DEPLOYMENT_SCOPE: 'production'
    MONS_STAGE: 'production'
    MONS_STORAGE_PREFIX: 'production'
    R2_BUCKET_NAME: 'mons'
    CLERK_SECRET_KEY: string
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'AI_GATEWAY_ID'
      | 'CLERK_PUBLISHABLE_KEY'
      | 'MONS_APP_SCHEMA'
      | 'MONS_CATALOG_SCHEMA'
      | 'MONS_DEPLOYMENT_SCOPE'
      | 'MONS_STAGE'
      | 'MONS_STORAGE_PREFIX'
      | 'R2_BUCKET_NAME'
      | 'CLERK_SECRET_KEY'
    >
  > {}
}
